### ISSUE TITLE
Missing authorization header or body parameter

### ISSUE THREAD

**Issue by dixonge** [voxpelli/webpage-micropub-to-github#110]
I tried to configure this the best I could, but I'm getting nothing. When I run the app on Heroku it just comes up as ```cannot GET /``` and when I try to access the endpoint I get ```{"error":"invalid_request","error_description":"Missing \"Authorization\" header or body parameter."}```

This is my first Heroku app, so I'm also rather confused by their interface. I successfully adjusted my github repo URL (just to test whether or not that needed a full URL) but have NO idea how to force Heroku to rebuild. 

Once again foiled by IndieWeb. :(

**Comment by dixonge** [comment]
Owner says they are busy - either way, this issue should have been closed a long time ago

**Comment by martineizayaga** [comment]
I'm getting the same error :(
