### ISSUE TITLE
Configurable post folders

### ISSUE THREAD

**Issue by paulrobertlloyd** [voxpelli/webpage-micropub-to-github#18]
Currently this service writes files to a `_posts` folder, but I use Jekyll’s collections feature to publish different post types to different collections. Is this something that could be configured (perhaps via Jekyll’s config file)?

In the simplest case, the ability to change the default post folder location would be great, but further improvements may allow users to configure multiple folder locations, perhaps based on post type?

**Comment by voxpelli** [comment]
This is actually very close to being possible: https://github.com/voxpelli/node-format-microformat/issues/6

I just need to tag a release there and then me or @keithjgrant if he is still up for it (or someone else) just needs to make a configuration here for the new option there (`filenameStyle`)

**Comment by voxpelli** [comment]
Related is also: https://github.com/voxpelli/node-format-microformat/issues/7 That's about supporting collections better

**Comment by paulrobertlloyd** [comment]
Oh, this is all excellent news! Looking forward to trying this again when these changes have been merged 😀

**Comment by voxpelli** [comment]
@paulrobertlloyd I pushed a new version, `0.5.0`, that add basic configurability to file paths. To solve your full needs we need https://github.com/voxpelli/node-format-microformat/issues/7 though – so I'll leave this open until that one is fixed, hopefully I can get to that soon.

Ping @keithjgrant

**Comment by voxpelli** [comment]
Now also https://github.com/voxpelli/node-format-microformat/issues/7 is fixed, so one can now add dynamic permalink and file path styles in an extension of the way added in https://github.com/voxpelli/webpage-micropub-to-github/issues/4

That means that one can now also set the env variable `MICROPUB_FILENAME_STYLE` to something like:

```json

[
  {
    "condition": "abc = 123 AND foo = bar",
    "value": "first/:slug"
  },
  {
    "condition": "content[] = \"hello world\"",
    "value": "second/:slug"
  }
]
```

The conditions are in a format supported by https://github.com/voxpelli/node-fulfills and it's applied towards the properties of the content. The first condition to be matched, that's the value that will be used.

This applies to `MICROPUB_MEDIA_FILES_STYLE` and `MICROPUB_PERMALINK_STYLE` as well + is also the new format for `MICROPUB_OPTION_DERIVE_CATEGORY`.

I know this may sound pretty complicated, but it shouldn't be that complicated. It enables a pretty powerful configuration-driven setup. I would very much want feedback on how it works.

@paulrobertlloyd Does this solve it for you? + is #17 required for this to be useful for you?

**Comment by paulrobertlloyd** [comment]
Hi @voxpelli. Sorry it’s taken so long to get back to you on this. I think this answers my original questions; I can configure the location in which files are written now, so that’s great. I have some other questions, but will post them in the appropriate threads.
