### ISSUE TITLE
Configuring layout value

### ISSUE THREAD

**Issue by paulrobertlloyd** [voxpelli/webpage-micropub-to-github#29]
Hello again Pelle. Great news! I have finally got this running on [my own site](https://paulrobertlloyd.com/journal/), meaning I can post from MicroPub clients, especially [Micro.blog](https://micro.blog). I love it! Now, to refine things a little.

Currently, posts are created with `layout: micropubpost`, but I would like to change this, ideally omit it (and use a default defined in my config), or change it to `layout: note`. Is this something that’s possible to do via `MICROPUB_OPTION_DERIVE_CATEGORY` (which still confuses me), or does this require a feature request?

Thanks again,

Paul

**Comment by voxpelli** [comment]
@paulrobertlloyd I've added this now 😉 Appreciate that it works well for you!

**Comment by paulrobertlloyd** [comment]
@voxpelli Oh wow, thanks! Just updated my repo, and works like a charm. Took a little figuring out that to disable adding a `layout` key I had to set `MICROPUB_LAYOUT_NAME` to `false`. I might add a note to the docs.

This also got me wondering about other aspects you might want to configure, and whether using environment variables is the right approach. Maybe a JSON/YAML file would be more appropriate? Not sure… it works for now, that’s all that matters.

Think I’ll next have a go at trying out [this PR](https://github.com/voxpelli/node-micropub-express/pull/12) to enable the media endpoint. Not being able to post photos to Micro.blog was a bit unexpected.

Thanks again!

**Comment by voxpelli** [comment]
@paulrobertlloyd A configuration file would most certainly be easier, but I don't want people to need to fork this repo to be able to deploy it to eg. Heroku – therefore the environment variables. Possibly could make both an option in a future.

Just a note – this endpoint do supports images, just not with the media endpoint as that standard didn't exist at the time 😉 

Updated the README with your suggestion 👍

**Comment by paulrobertlloyd** [comment]
> this endpoint do supports images, just not with the media endpoint as that standard didn't exist at the time

A-ha! Well, that’s promising. Looking at the PR I mentioned, looks more complicated than I realised. Would merging that PR into a fork of node-micropub-express, and updating my fork of this repo to point to that fork, be enough for the media endpoint to work? Or would I need to set up a `mediaHandler` too? Or even more than that?
