### ISSUE TITLE
Support custom permalinks

### ISSUE THREAD

**Issue by barryf** [voxpelli/webpage-micropub-to-github#3]
Hey Pelle. Love this. I've successfully got it working using a test repo on my GitHub and Heroku accounts and can post via Micropublish and Quill. 👍 

Small issue: after a successful post, the Location header followed a `/:categories/:year/:month/:title/` permalink method which doesn't match my GitHub Pages config. I was taken to the 404 page because my (default?) config uses `/:year/:month/:day/:title.html`.

So you may want to allow the permalink method to be specified via a Heroku config key.

**Comment by voxpelli** [comment]
I totally agree. The endpoint should absolutely support different permalink formats. I'll look into making that customizable.

**Comment by voxpelli** [comment]
This has now been implemented in the format-microformat module: https://github.com/voxpelli/node-format-microformat/blob/0.7.0/CHANGELOG.md#070-2016-07-16
Thanks to a new module I created: https://github.com/voxpelli/node-jekyll-utils

Now what remains is just hooking it into this module.

**Comment by voxpelli** [comment]
This has now been solved in `0.3.0`, in part thanks to @lildude who added the basis for it in a fork of his, which I took the liberty of building upon and merging in.

In addition to the basis I also added in auto-configuration, which means that the app itself will look at the `_config.yml` that's in the repo and figure out the permalink style from that.

So no need to configure anything, the new permalinks will just work out of the box. But if one wants to override the defaults one of course can and one can also disable the auto-configuration altogether if one wants.

**Comment by voxpelli** [comment]
Released a bug fix as `0.3.1` as the caching of the automatic configuration wasn't working in `0.3.0`

**Comment by lildude** [comment]
You weren't meant to see that until I was finished 😉 Glad to see it was useful and motivational.

**Comment by miklb** [comment]
Sweet. And nice to see a familiar nick, @lildude

**Comment by lildude** [comment]
😍 @miklb I was just about to tweet you about this. You intro'd me to the whole IndieWeb stuff (via Twitter) and now I'm starting to dig my oar in.

**Comment by barryf** [comment]
@voxpelli Reading the `_config.yml` file for permalink style is a much better solution than my suggestion. I'll work on adding that approach to Webhook Mentions.
