### ISSUE TITLE
Create separate permalink option for media files

### ISSUE THREAD

**Issue by pmarsceill** [voxpelli/webpage-micropub-to-github#30]
I host my site's source files in `src/`, so my media filename env var is:
`MICROPUB_MEDIA_FILES_STYLE=\"src/assets/microblog/:year-:month-:day-:filesslug\" `

but when the site is compiled, the media files are available via URL at this kind of format:
`https://example.com/assets/microblog/:year-:month-:day-:filesslug`

The current implementation assumes that these two are equivalent and uses the former in the YAML frontmatter of the post file that it generates, when I would like it to use the latter. It would be nice if there were two options (similar to `MICROPUB_FILENAME_STYLE` and `MICROPUB_PERMALINK_STYLE`) for media files... One for the filename (used when uploading media) and one for the permalink (used for referencing the files via URL after the site is deployed).

**Comment by keithjgrant** [comment]
I would love to have this, too

**Comment by voxpelli** [comment]
Related: https://github.com/voxpelli/node-format-microformat/issues/3
