### ISSUE TITLE
Improve documentation for .env settings

### ISSUE THREAD

**Issue by lewisnyman** [voxpelli/webpage-micropub-to-github#6]
Hey, thanks for making this. I'm working on setting it up now.

Maybe it's just me, but I'm a little confused on what the correct values are to enter for each setting. Maybe some comments or a link to another page would help? I'll try digging through the code and figure some of them out.

**Comment by lewisnyman** [comment]
I noticed there are comments in app.json, maybe the least that can be is to point people to that file

**Comment by voxpelli** [comment]
Sorry for that! Should totally add some comments in README and/or sample.env

**Comment by voxpelli** [comment]
@lewisnyman I added some documentation now. Is it enough for them or do you think I should add more?
