### ISSUE TITLE
Authenticates but won't post

### ISSUE THREAD

**Issue by jbpyn** [voxpelli/webpage-micropub-to-github#63]
I'm struggling here. If anyone can help. I can authenticate without any trouble, but I can't get any further with Quill or Micropub.rocks. I'm using Netlify, if that makes any difference? 

This is a problem with formatting though, right? 

HTTP/1.1 400 Bad Request
Server: Cowboy
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Content-Length: 11
Etag: W/"b-EFiDB1U+dmqzx9Mo2UjcZ1SJPO8"
Date: Sat, 01 Sep 2018 03:48:50 GMT
Via: 1.1 vegur

Bad Request

Any help appreciated, I'll send you a chocolate fish. No seriously, if you want one.

**Comment by jbpyn** [comment]
Never mind, fixed it. I'll eat the fish myself. :)

**Comment by MattSLangford** [comment]
@jbpyn What did you do to fix? I'm having the same issues across the same services.

**Comment by jbpyn** [comment]
If I remember correctly,  I was using the full github address for the repo but all it needed was the name.  e.g Instead of jbpyn/micro once I just entered micro it started working. Let me know if that doesn't work, I will post my settings for you.

**Comment by MattSLangford** [comment]
Looks like I have that set right. I've used this before on older sites with no issues, but I can't figure it out today for anything. Probably something stupid I'm just overlooking. If you don't mind, I'll reference your settings. Thanks.

**Comment by jbpyn** [comment]
[Screenshot of the settings ](https://f001.backblazeb2.com/file/jbpdropshare/x3Ms1d8tBYnhoERV9Jvdk5MPLHMZaz5nF8KWByfjGdsHneEJH3MijenAxonlxtvTkXY61QTVz6hSR27E0ynkVb1cnOoHtBxv5DEs.png) hope this helps

**Comment by jbpyn** [comment]
I know the feeling well!

**Comment by MattSLangford** [comment]
Thanks. I finally got it working. Stupid me had a duplicate line in _config. There goes 3 hours of my life.
